# Generated by Django 5.2.2 on 2025-11-03 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_customuser_tipo_alter_documentoestagio_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoestagio',
            name='assinado_por_aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_assinados_aluno', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentoestagio',
            name='assinado_por_diretor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_assinados_diretor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentoestagio',
            name='assinado_por_orientador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_assinados_orientador', to=settings.AUTH_USER_MODEL),
        ),
    ]
