# Generated by Django 5.2.2 on 2025-11-03 17:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_documentoestagio_assinado_por_aluno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoestagio',
            name='codigo_verificador',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, help_text='Código único para verificação pública', null=True),
        ),
    ]
