# Generated by Django 5.2.2 on 2025-11-03 17:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_documentoestagio_codigo_verificador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoestagio',
            name='codigo_verificador',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Código único para verificação pública', unique=True),
        ),
    ]
