# Generated by Django 5.2.2 on 2025-11-03 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_documentoestagio_codigo_verificador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='GradeMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('BASE', 'Base Comum'), ('TECNICA', 'Técnica')], max_length=10)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_materias', to='core.curso')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='em_grades', to='core.materia')),
            ],
            options={
                'unique_together': {('curso', 'materia')},
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='materias',
            field=models.ManyToManyField(related_name='cursos', through='core.GradeMateria', to='core.materia'),
        ),
    ]
