# Generated by Django 5.2.2 on 2025-11-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_materia_nome_grademateria_curso_materias'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoestagio',
            name='foto_3x4',
            field=models.ImageField(blank=True, help_text='Foto 3x4 do aluno para a ficha.', null=True, upload_to='fotos_3x4/'),
        ),
    ]
