# Generated by Django 5.2.2 on 2025-11-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_documentoestagio_foto_3x4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoestagio',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho (Pelo Aluno)'), ('RASCUNHO_ORIENTADOR', 'Rascunho (Pelo Professor)'), ('AGUARDANDO_ASSINATURA_PROF', 'Aguardando Assinatura (Professor)'), ('AGUARDANDO_ASSINATURA_DIR', 'Aguardando Assinatura (Direção)'), ('CONCLUIDO', 'Concluído'), ('REPROVADO', 'Reprovado (Pendente de Correção)')], default='RASCUNHO', max_length=30),
        ),
    ]
