# Generated by Django 5.2.2 on 2025-11-29 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_documentoestagio_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_confirmado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='token_confirmacao_email',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.DeleteModel(
            name='Nota',
        ),
    ]
