# Generated by Django 5.2.2 on 2025-11-30 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_customuser_codigo_2fa_customuser_codigo_2fa_expira_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='token_recuperacao_expira',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='token_recuperacao_senha',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
