# Generated by Django 5.2.2 on 2025-11-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_customuser_token_recuperacao_expira_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='usa_google_authenticator',
            field=models.BooleanField(default=False),
        ),
    ]
