# Generated by Django 5.2.2 on 2025-11-30 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_customuser_usa_google_authenticator'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoestagio',
            name='data_encaminhamento_aluno',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
